### ISSUE TITLE
Tests out of order

### ISSUE THREAD

**Issue by DoriansGrave** [learn-co-curriculum/bringing-it-all-together#32]
"new_from_db" has to be in front of "find_by_XX" in testing order, otherwise TDD doesn't make any sense.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#34. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @DoriansGrave,

Thank you for reporting this issue. We've updated the order of this lesson's test so that it is clearer that students first build the `.new_from_db` necessary for `find_by_id`, rather than having to use the create method, and believe this issue is now resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
