### ISSUE TITLE
Seems very out of date.

### ISSUE THREAD

**Issue by CatalanoWebDevelopment** [learn-co-curriculum/bringing-it-all-together#33]
I needed to use a create method when finding an id already inside of the database. This doesn't seem very logical or straightforward whatsoever. Even after talking with a technical coach, I am still left confused.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#34. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @CatalanoWebDevelopment,

Thank you for reporting this issue. We've updated this lesson's tests so that it is clearer that students first build the `.new_from_db` necessary for `find_by_id`, rather than having to use the create method, and believe this issue is now resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
