### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/bringing-it-all-together#34]
PROBLEM: Tests out of order. See issue #32 
NOTIFY: @DoriansGrave

PROBLEM: Clarify process. See issue #33.
NOTIFY: @CatalanoWebDevelopment

**Comment by maxwellbenton** [comment]
All four referenced issues have been fixed in master and rebased into solution. Two users listed above were notified in their issues.

- miss DROP TABLE / ::create_table in dog_spec.rb = fixed in earlier updates
- Tests out of order / Seems very out of date = issue due to bad ordering of tests, fixed by reorder
